### ISSUE TITLE
Download csv button in admin lists

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#101]
Setup functionality to download any admin list. Use any open source development. There must be something available.

Ideally, when clicking on that download button, a list of fields will appear. Those would be all the fields shown in the detailed page. User should be able to decide which ones to include in the report. If that's is too complex, just include all fields by default.

In the future that request will not processed immediately but added into a queue if it requires too many resources

**Comment by marcosmenendez** [comment]
It has already been built by @atrandafir in the transactions view here: https://www.thegooddata.org/transactions/admin so it is a matter of adding it to every list in admin. A couple of comments about it:
- It is not exporting other alphabets. It is important at least in the members pii to be able to export Cyrillic, Japanese, hindu, etc
- it is exporting the file in excel. If it is easier or requires less resources to do it on csv, please change to csv

**Comment by JuanMenendezBuitrago** [comment]
I've tried to use the same code that is in the tansactions section but it doesn't work well with the adtracks,browsing and queries tables because it runs out of memory. I think it's because it generates the file on-the-fly and it consumes too much memory.

I'll try to:
 * Export to CSV instead of Excel.
 * Generate a temporary file and then send it to the user

**Comment by atrandafir** [comment]
The code that I've put in Transactions uses a very lightweight Excel format. It's basically like a CSV but the file is served as a XLS, so that format is not the problem. But I agree anyway into switching to CSV, I had put it to XLS because some Excel programs do not open very well CSV files.

Anyways so feel free to use CSV, I think php has some built-in functions for that.

Now I see you want to export AdTracks, Browsing, Queries. I would not export those tables unless it is really necessary, because the tables will grow huge in time and I don't see the point in exporting them unless we really need to do something with that information.

If we still need to export them you should use the following code to increase limits:
set_time_limit(300); // execution time limit in seconds
ini_set('memory_limit','512M'); // script memory limit

Or consider exporting them with some command directly from Postgre.

**Comment by marcosmenendez** [comment]
You are right, lets not export those. Those could only make sense exporting if the could be filtered first.

Let's export the rest of them (loans, etc). Thanks

**Comment by JuanMenendezBuitrago** [comment]
The problem with UTF-8 or UTF-16 is that Excel doesn't recognize them automatically when opening the file. You have to import it and specify what encoding you'r expecting (UTF-16).

If the file is opened in a text editor such as notepad or sublimetext, the cyrillic, hindu etc the characters are correctly shown. (Not now, but with the upcoming implementation they do).

**Comment by JuanMenendezBuitrago** [comment]
![export](https://cloud.githubusercontent.com/assets/5305439/5799512/6165d2e4-9fd3-11e4-8f97-472da6a5286d.PNG)

**Comment by marcosmenendez** [comment]
Export does not work. Try here: https://www.thegooddata.org/user/admin/#

**Comment by JuanMenendezBuitrago** [comment]
It was related to #88 as there was a missing file which I have uploaded recently.
