### ISSUE TITLE
Changes in good-data achievements

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#108]
The summary of achievements at the good-data page should change to the following:

Company achievements
- Monthly Active Users
- Registered Members
- Monthly Visits Stored (count of visits done by our users that have been stored in our server last month)
- Monthly Threats Blocked (count of web threats blocked last month
- Monthly Queries Traded

Good investments
- Total Money earned (we should put the net value instead of gross value taking away commissions of every income)
- Money Lent
- Money Repaid
- Money Lost
- Outstanding Portfolio

Good projects (leave it as it is now)

Review the caching of all variables to ensure that we are not overloading the server, but that we are still offering updated figures (at least, daily updated)

**Comment by marcosmenendez** [comment]
Most of the changes are wrong. The numbers do not show what the title says (visits, queries, etc)

Please revert this change and show previous version until requirements are well understood and development is properly done

**Comment by bodiapz** [comment]
Ok, I have reverted the changes

**Comment by bodiapz** [comment]
I have fixed, please check

**Comment by marcosmenendez** [comment]
Where can I? It is not in pre, and in fact pre does not have enough data @agonbar has to copy at some point database as issue #56 says 

@atrandafir , can you check the code please?

Thanks

**Comment by atrandafir** [comment]
@marcosmenendez yes I'll try to check, but even if I try it locally if we are going to keep using pre we should ask @agonbar to look into issue #56 and provide me with sufficient access so I can copy the database from prod to pre at any time we need it

**Comment by agonbar** [comment]
@marcosmenendez in order to install a regular backup of the database we
need to save it in a different server, either Amazon or an unused one ir
our network. This should be decided in a call as is quite long and
complicated.
For now, the developers can export the database and load it on pre with the
mysql command, or is that a problem (I can create a script for that if it's
too complicated)?

El Tue Feb 10 2015 at 15:59:46, Alexandru Trandafir Catalin (<
notifications@github.com>) escribió:

@marcosmenendez <https://github.com/marcosmenendez> yes I'll try to check,

**Comment by marcosmenendez** [comment]
I've responded to @agonbar comment on the issue #56 he is referring to. read here: https://github.com/thegooddata/webapp/issues/56#issuecomment-73876628

**Comment by atrandafir** [comment]
@bodiapz just checked this and looks fine to me

**Comment by marcosmenendez** [comment]
It is not fine. There should be 5 items per column. First column has 6. Please review that items are the ones requested in terms of naming and of content

**Comment by bodiapz** [comment]
This changes was rewritten after yesterday marge. I have fixed it and commited again.

**Comment by atrandafir** [comment]
Hello both, I apologize to you all, it looks like the merge I've done yesterday affected negatively on some of the files.

A while ago when we deployed to production the minScript extension, it gave us problems so in order to fix them quickly I did the changes directly on master.

That's why yesterday I've decided to bring those changes back from master to develop so we have the latest code on develop too.

Looks like some files gave me conflicts and when I've merged them the end result was not correct.

We can see here the commit:
https://github.com/thegooddata/webapp/commit/c6e8b766a4cebc73cc587b5a028c37c97c0e50b7?diff=unified

And the files that were in conflict:
TGD/protected/controllers/GoodDataController.php
TGD/protected/helpers/ExcelHelper.php
TGD/protected/views/goodData/index.php
TGD/themes/tgd/js/admin.js

The ones that resulted in a wrong merge affecting this issue:
TGD/protected/controllers/GoodDataController.php
TGD/protected/views/goodData/index.php

And other files are:
TGD/protected/helpers/ExcelHelper.php
TGD/themes/tgd/js/admin.js

Those last two I think they merged correctly but I will check and restore them from develop if I see any problem.

I'll do the deploy to pre again right away so you @marcosmenendez can test it properly.

I hope now when we'll merge from develop to master in order to deploy to production we won't run into a conflict again. I will be careful with that.

**Comment by atrandafir** [comment]
Update: Just did the new deploy to pre so you can check it again.

**Comment by marcosmenendez** [comment]
Doesn't work. I've updated the income and the loan table but the numbers shown in good-data page have not been updated

**Comment by atrandafir** [comment]
One things comes into my mind. I think this data has been cached by @bodiapz so that's why you might not see any change in the same day.

**Comment by marcosmenendez** [comment]
Yes, that's what I thought. But caching income and loans is pointless. Visits, threats and queries may make sense. Not the rest.

**Comment by bodiapz** [comment]
Yes, Alex right. Loans is cached. So no problem for me to remove income and loans caching.

**Comment by bodiapz** [comment]
Caching of loans removed. Changes appears right after change

**Comment by marcosmenendez** [comment]
Money earned is not working anymore. I just requested to take out expenses of the income sum. There is only one income of 206, expenses=6. Money earned should be 200, not 150.75

Regarding queries traded, It says that we have traded 1, but if I go to the admin view https://pre.thegooddata.org/queries/admin?Queries_sort=id.desc and I see the last query, it is older than 1 month. Are we doing it correctly?

**Comment by bodiapz** [comment]
In issue #60 you have wrote another formula "Sumation of ((income - expenses) * money reserved/100)". 
Queries traded count fixed.

**Comment by marcosmenendez** [comment]
That was the calculation of a different variable that was shown in the previous version of the page called "money reserved for microloans". We are not showing that variable in this page. We are showing the "money earned" that is a different thing, so the formula is different as well.

By the way, according to that formula, "money reserved for microloans" should equal (206-6)*50/100=100, not 150.75

**Comment by bodiapz** [comment]
It is 100 GBP converted to 150.75 USD.

Formula changed to previus state.

**Comment by marcosmenendez** [comment]
You are right. My fault. Let's use the right formula though. Sumation of (income - expenses)

**Comment by marcosmenendez** [comment]
Under certain circumstances the first column is shown with all zeroes. Maybe when first login in, or when changing user.
