### ISSUE TITLE
Are we serving fonts properly?

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#115]
I've seen that proxima nova fonts usually take a long time to download. I wonder if they are properly installed in our server and if we can do anything to speed up the download. They should be used for all subdomains including www, blog and collaborate

It is not a big experience problem, but has some impact in SEO. I thought would be to use Amazon cdn or cloudfront just to serve the fonts.

If you need fonts documentation please ask

**Comment by atrandafir** [comment]
For me they seem loading properly so I'm not sure if we should bother to move them to a CDN. 

As for download speed, maybe on slow connections the fonts take longer to load but that would happen with any font. 

Right now the webapp loads 160kb of fonts. Looks there are 4 versions of the font and each of about 40kb:

- ProximaNovaSoft-Medium
- ProximaNovaSoft-Semibold
- ProximaNovaSoft-Bold
- ProximaNovaSoft-Regular

Possible optimizations:

1) Check if we really need to load them all, or one would be enough, for example the most used looks to be ProximaNovaSoft-Regular but don't really know if it depends on the others.

2) Enable gzip if we keep them on our server:

For each font there are three files, ttf, wof, eot but only one is loaded depending on browser support. 

Woff is compressed by default but the other 2 tyes used by older browsers could benefit in download speed if the webserver uses gzip on them:
http://blog.bigdinosaur.org/gzipping-at-font-face-with-nginx/

3) Avoid reloading fonts when navigating from webapp to blog or collaborate, by pointing them all to the same URLS (either own server or cdn)

4) Moving to a CDN would free bandwidth and connections to webapp server

As for "reducing requests to server" I consider this a frontend optimization process and we should keep in mind that right now only on webapp we're unifying css/js files, but there are lots of other files, images for examples that could be put into CSS sprite to load only one instead of multiple files. And also the Blog and Collaborate are not optimized to reduce requests, they load a lot of files.

Well let me know if you want to apply any of the possible optimizations.

**Comment by marcosmenendez** [comment]
Ok. If you think it is not a big issue I'd implement the lowest effort ones. Maybe 2 & 3?

It happened to me that I got the message saying it was waiting for the fonts, but since we don't depend on SEO it is not a big deal. Your call

**Comment by atrandafir** [comment]
Okay, just created separate issues that would do point 2) and 3) and assigned them to the corresponding team members.

I'll close this issue now. If you think we should keep it open just open it again.
