### ISSUE TITLE
Update phplist segments with user data

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#116]
Update segments called "Member legal comms" (id=25) and "Pre-accepted legal comms" (id=24) with email of accepted and pre-accepted members of the webapp.

Everytime there is a change of status of any user, or there is a new user that is pre-accepted, those segments should be recalculated. For instance, when the user resigns, or when he pays his share

**Comment by JuanMenendezBuitrago** [comment]
So far, I've implemented the changes in  the following user status: APPLIED, PRE-ACCEPTED and ACCEPTED. I can create the PHPList lists for the rest of status if you want, and implement the rest of changes.

**Comment by marcosmenendez** [comment]
No need for applied. Just pre & accepted. Should be based on changes on database, not triggered by website or extension actions. Please ask Alex to implement properly

**Comment by JuanMenendezBuitrago** [comment]
If you want to implement this as low-level and close to the database as possible, the only solution I can come up with is using triggers but I'm not sure how to do it. I guess I should implement a trigger on update that could use the REST API to update the PHPList values depending on the old and new status of the user being updated. Probably I should use pl/php to write the function and do a curl call from it but before I begin with it I would appreciate some opinions from @atrandafir or @bodiapz in case they've had any experience with similar cases.

**Comment by marcosmenendez** [comment]
@atrandafir and @bodiapz, you have been asked for opinion, so please respond even if you don't have any. This issue is linked to #145 so I'll assign both to @bodiapz

**Comment by atrandafir** [comment]
Hi everybody, sorry I have missed the mention on this issue. 

My feedback on the approach of keeping PHPList segments updated based on user data:

- What @JuanMenendezBuitrago developed so far I think it is great I mean we already have a basic way of how it must work and the way to communicate with PHPList.
- But since we want it to be always updated no matter from where we modify I would remove all the code from the User Edit form and put it inside a Command line tool that will be setup on daily or hourly cronjob.

There is no need to put all this code as some kind of triggers in the webapp because maybe sometimes PHPList will not be available and could result in a error or maybe will reduce performance.

So the approach with the yiic command and the cron job:  

1. We should add some fields to the user table to store the corresponding segment and to be able to know when it has changed and if must be added/updated to avoid updating if it did not change
2. We select only all the users that must be added/updated to PHPList
3. We run the corresponding add/update request per every user

From a performance point of view, with proper fields on the table to know when we must run requests to PHPList and with a limited number of requests per every process the command will result in a good way to maintain the information updated.

We could call it.. phplistsync :)

**Comment by marcosmenendez** [comment]
I reassign it to @JuanMenendezBuitrago but please have a look later at issue #145 and explain to @bodiapz any relationship between the 2 when handling phplist segments/lists

**Comment by JuanMenendezBuitrago** [comment]
I've implemented another approach which I think is simpler. I just moved all the PHPList-related logic to the User model's afterSave(), afterDelete(), afterFind() and afterConstruct() method. In the methods afterFind() and afterConstruct() it simply gets the original data. Then every time the user's data is updated or inserted, it goes through the afterSave() method which  compares the original data with the new data and handles the PHPList changes accordingly.

Before, everything was taken care of in various controllers (AdminController, ProfileController, PurchaseController...).Now, regardless of where the user's data is changed the PHPList segment should change (if the user's preferences are set to notify the user).

I've noticed there are two lists for each pre-accepted and accepted status, but I' not sure what is the purpose of them.

**Comment by JuanMenendezBuitrago** [comment]
Sorry for not having mentioned it before implementing it but I was a bit late with this issue and wanted to commit as son as possible. I've tested it locally but I haven't deployed it to pre so I can say if it works there. I changed config.php in pre and prod to add a couple of constants for the two PHPList segments that I didn't know about.

**Comment by bodiapz** [comment]
Ok, thank you Juan. I will rebuild my scripts (pre-accepted and accepted), to fit new logic
