### ISSUE TITLE
Detect and store user country in webapp

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#118]
We should change current IP masking mechanism so we can record the country code of the visitor either in the user table or in the transactions table (the 2nd one would be more accurate since there may be users moving from one country to another). In case we record it for each transaction I would update it daily, not calculating the country for every transaction. How to obtain the country code is explained here https://piwik.thegooddata.org/index.php?module=UserCountry&action=adminIndex&idSite=1&showaddsite=false

There are 2 ways I can think of preserving user anonymity:
1. Either we keep on hashing the whole IP, but we only do it after recording the country that this IP relates to
2. Or we mas last 2 numbers from the very beginning. This second option will untap again the risk of trolls creating new accounts artificially

**Comment by atrandafir** [comment]
@marcosmenendez I've just assigned this issue to myself.

As to reply to your latest email on this task:

There is no table where we store extension preferences of anonymous users.

There IS a table where we store ext. preferences for registered members so preferences get restored when they login again.

And.. there IS a table of ACTIVE USERS. This table was created in order to track how many users were using the extension, be it registered member or anonymous user.

We can use this same table for now and add the country field to this table and store it here for now. If in the future we think of a better place to store it we would change it.

PS: This is the same table where we were hashing the user's IP.

I will look into the detection method and let you know if there is anything else to talk about.

Also, I understand that now we'll be just storing data and I guess in a future issue we'll display that data somewhere.

**Comment by marcosmenendez** [comment]
Fine for me. Yes, the idea is to build some analysis in the future based on that data and present it.

**Comment by bodiapz** [comment]
Please, give me login and  password to piwik on pre-production

**Comment by atrandafir** [comment]
@JuanMenendezBuitrago do we have a Piwik for pre-production? 

@bodiapz I think we only have it for Production. I'm sending you the details by mail now so you can login.

**Comment by atrandafir** [comment]
Hey @bodiapz just deployed this to production and sometimes it shows the following error in the logs:

2015/04/24 19:01:20 [error] [php] Undefined index: MT (/srv/webapp/releases/20150424184331/protected/extensions/geoip/GeoIP/CRN.php:4519)

Looks like it is trying to detect some region that is not defined, and instead of returning null, is giving an error because there is no prior check to see if the array keys are set or not, it just returns them but when data is missing it will give that undefined index error.

**Comment by marcosmenendez** [comment]
I cannot test it since country data is not visible in the admin panel. Please include that field in the Member view
