### ISSUE TITLE
Calculation of daily totals to optimize requests

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#124]
Evil data, good data and your data require to access plenty of dynamic data. Even if it is indexed or cached, it is not scalable.

An extra action would be to calculate and store daily subtotals of the different metrics, so whenever a user request a page, only the new data has to be counted and summed up to the previously calculated subtotals. These subtotals will need to be stored for the last 30 days in case of metrics that are shown for that period. There are other metrics that show a full year evolution. In that case we may need to keep the last 365 days of a user.

Older daily subtotals can be deleted.

Please discuss with @atrandafir before developing it

**Comment by marcosmenendez** [comment]
@atrandafir I assume you will test it. I cannot. Please change status once done

**Comment by JuanMenendezBuitrago** [comment]
Sorry, the commit I made was for issue #142, not for #124. Ignore the reference.

**Comment by atrandafir** [comment]
My feedback on this issue and general optimization of Evil Data page..

Some improvements were made, but:

1) Evil data page is still incredibly slow

For users with plenty of data the load times are very slow and result in a response timeout, you have to refresh the page many times until the cache is finally built and then it loads fast because it is cached.

This has been tested in Pre with the fake data generated and with any of the existing users, before testing the cache tables were truncated from Admin.

2) There was no daily caching system created as issue description requires

I understand the issue requested caching some data grouped day by day in order to minimize the data sets used in calculating the final results and speed up everything. 

I see nothing like that done even so I know that in order to accomplish it, mostly the whole thing should have been rebuilt almost from scratch.

3) I think "Your risk profile" section has a bug

Now when seeing "Percentage of threats allowed" it shows -1% for You and 0% for TGD. Tested with two different users.

So this being said, in order to Deploy it we should do some more testing to at least make sure we don't break anything that was already working.

Then I would leave it as it is and consider creating another issue and rewrite the whole Evil Data requests from scratch and the way we will cache them to have good performance results.

Last things to add:  

- Maybe we should evaluate if we need to move to a different database system for the future.
- We should also keep in mind that server resources and configuration affect performance, so we can't expect too much from a server with low RAM and no tweaking in configuration, that has to handle a database that grows bigger every day.

**Comment by atrandafir** [comment]
@marcosmenendez Changing the database system is a important step, since we're not very familiar on working with big databases we should really study it very well. 

I'm sure we can stick with Postgre for a while, and apply all the possible optimizations but we must also evaluate if we need to make a switch in the future to avoid repeating work if we're finally going to change it.

I guess a kind of NoSQL database would be the option, but as I say we should read about all the available ones and which matches better our application's requirements.

I will create the new issue to rebuild Evil Data, as for the new database system, we should study the subject, meet and talk, and decide new steps.

**Comment by atrandafir** [comment]
@bodiapz Nevermind point 3 for now, I'm testing in Production and looks like data shows correctly for risk ratios. I've removed the rejected status since this has been deployed to production too and for further improvements on this page we've got a new issue:  
https://github.com/thegooddata/webapp/issues/148
