### ISSUE TITLE
Improve internal emails formatting

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#127]
Formatting of emails sent by our system could be improved according to mail-tester.com to avoid spam filters
![screen shot 2015-02-23 at 3 14 42 pm](https://cloud.githubusercontent.com/assets/1178350/6330351/676deb24-bb6f-11e4-8efb-6e1f821d6ed8.png)
. Improvement areas attached.

**Comment by atrandafir** [comment]
@bodiapz I have removed one of your changes in setBody method of the mail component because when testing the "Send errors by email" feature it was generating in Gmail a "noname" file instead of the actual message. I think it was because of a small typing error: "$contentType = 'html/text'".

And I also did not really understand the reason why that code block was added so removed it for now. Feel free to add it again if you think it is necessary.

**Comment by atrandafir** [comment]
I think there's not much to test for now. As far as I understand the 1st and 2nd points in the picture:  

1. Just requires us to wrap the html message into '<html>' tags so it is a full html document not just a part. So we could maybe add a check somewhere to see if no '<html>' tag exists to automatically wrap the message with '<html><body>message</body></html>'

2. When we send HTML messages we should see how we can do with Swift mailer to also attach a text/plain version of the message built from the original HTML message.

3. Not really know what it means so we should read about it first

**Comment by atrandafir** [comment]
Tested. Got 9/10 because we're on a spam list. But I guess it is because of Amazon gets sometimes in those lists.
