### ISSUE TITLE
New landing

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#162]
In order to make our service more understandable we are going to redo the landing using this wireframe: https://beta.moqups.com/thegooddata/OC4z975PTd/edit/page/a011ec86a

When we implement it we will probably drop the partners page (it does not apply anymore) and may review the menu structure

**Comment by atrandafir** [comment]
Updating the task description so that @jorgeheavydots can implement the new landing correctly.

As we know @ibenzal has been working on a new Home page.

When he started to work on it I have somehow prepared a way for him to be able to add the new html and css without touching any php code of the original website.

So basically what I did was: "Right click on home page > View source code" copied the code and saved it as: https://github.com/thegooddata/webapp/blob/develop/TGD/themes/tgd/new/index.html

So then @ibenzal started to work on that file and also added some new assets, (css, js, images).

So what we need to do now is to manually merge back the code of the new Homepage into the current Homepage inside php/yii.

Here are a list of things to keep in mind when integrating the new home page:  

- We should use a parameter called "showNewLanding" that will be set to false in production by default, and set it to true locally, and keep both landing pages working at the same time if possible so this way if we must deploy to production and it is not finished there will be no problem, the old home will be displayed.

- The new landing uses a different verson of bootstrap (js and css), in order to keep both versions of bootstrap and not break the rest of the page, we should somehow with a parameter inside the main controller, be able to specify for the index action what bootstrap version to use, and that will change the files that the bootstrap package will load. Here you can see what the current bootstrap package looks like, I think we can override it at runtime from the parent controller:
https://github.com/thegooddata/webapp/blob/develop/TGD/protected/config/common.clientScript.php

- We must link the new assets properly the Yii-way, secifying the theme base url: <?php echo Yii::app()->theme->baseUrl; ?> and using the CClientScript component if we need to register any new js/css.

- Keep in mind that the layout has "two statuses", the one when the user is logged, and the one when the user is not logged, please test both and make sure both work.

- Make sure the new buttons work, such as the ones to get the extension because I think while @ibenzal was working on the new home we changed the way users can install the extension.

- Make the "blue bar" with statistical information use real data from our database, probably the recommended way would be to make a implementation similar to Good data page, using a Ajax request to load the stats.

I think that's all, when done we can publish to PRE, test, and then deploy to PROD.

For any questions regarding the new code please contact @ibenzal and for questions regarding Yii/Webapp me and @JuanMenendezBuitrago can answer.
