### ISSUE TITLE
Company achievements not always displayed

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#169]
"Sometimes" when visiting https://www.thegooddata.org/good-data the column of company achievements is blank, as shown in the picture.

After some minutes this column is filled out automatically. I wonder if it has something to do with the caching of data.
![screen shot 2015-06-07 at 10 19 15 am](https://cloud.githubusercontent.com/assets/1178350/8023173/20674162-0cff-11e5-8f89-971efbde684d.png)

**Comment by JuanMenendezBuitrago** [comment]
I can't reproduce the behavior now but I've seen it before and it was
caused by an "error 500" when requesting for
https://www.thegooddata.org/goodData/CompanyAchievementsData. So it was
something on the server side but I can't give more details. Maybe @agonbar
can take a look at the logs and find out the reason, because I have no
access to the logs.

2015-06-07 10:23 GMT+02:00 Marcos Menendez <notifications@github.com>:

**Comment by JuanMenendezBuitrago** [comment]
I'll check that the data caching is working fine. It's all I can do for now.

**Comment by agonbar** [comment]
I'll need the day/hour, the most precise one you can give me, thnx.

**Comment by JuanMenendezBuitrago** [comment]
I think I already solved the issue that caused the error 500 that I mentioned previously. It was due to the fact that after a deployment, there were some migrations pending. Therefore the problem is caused by something else.

I think the cache works fine. It keeps the values stored for 24hrs. So the solution would be to implement a script to be called by a cron job every 23hrs for instance, that would refresh the values in the cache and extend the expiration time.

**Comment by marcosmenendez** [comment]
@JuanMenendezBuitrago in case you are proposing a new issue, please ad it and link it to this one. And mark this one as closed, ready to test or whatever. Thanks

**Comment by JuanMenendezBuitrago** [comment]
No, it was still the same issue. I just wanted to tell @agonbar that the issue was not related to the error 500 that I mentioned previously.

I've just pushed to github a new command that should be run via cron job every 23hrs (any amount less than 24hrs). The command is:

    php /srv/webapp/current/protected/yiic RefreshCompanyAchievements

**Comment by UchihaCFC** [comment]
I delimited seconds it takes for a query and schema to the database to reduce waiting time, related to issue # 171 when I got to a limited number of queries it can not be trapped while.

To strengthen @JuanMenendezBuitrago solution. I have not tested too much data, but between one thing and another should not be trapped in the query.
