### ISSUE TITLE
Update exchange rates automatically

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#49]
In order to maintain exchange rates to GBP of all currencies we should setup a daily cron job that will look into some API (Google?) and import fresh exchange rates.

**Comment by JuanMenendezBuitrago** [comment]
I've finished an UpdateRates command now that will update the rates in currencies table with the rate of the GBPXXX pair, being XXX the code of the currency in the currencies table. A cron job should be added so that it calls this command in the following way (if from TGD folder):

$ protected/yiic UpdateRates

**Comment by JuanMenendezBuitrago** [comment]
@atrandafir take a quick look at it if you have the time.

**Comment by atrandafir** [comment]
@JuanMenendezBuitrago it looks fine to me, haven't tested it locally but the implementation looks correct. A quick note, since you're creating a console command, you could use "echo" to print some information about what is going on. Like..  

    echo "Currency {$code} was updated with value: {$value}\n";

You could also optionally create a command param with name "debug" and set it by default to 0, and then create a private function named debug() that will only print on screen if you use --debug=1 when calling the command.

Anyways if you just print stuff on screen with echo there will be no problem when configuring cronjob because we can make it send it to dev/null.

**Comment by atrandafir** [comment]
@JuanMenendezBuitrago I just tried to setup the cronjob in production and I've got this error when running the command.

Looks like the API returns some text instead of a number in some case and that causes a sql error when trying to update the value in the database.

tgd@lnd-app00:~$ php /srv/webapp/current/protected/yiic.php updaterates
exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type numeric: "N/A". The SQL statement executed was: UPDATE "tbl_currencies" SET "exchange_rate"=:exchange_rate WHERE code=:code' in /srv/webapp/shared/yii-1.1.14.f0fee9/framework/db/CDbCommand.php:358
Stack trace:
#0 /srv/webapp/shared/yii-1.1.14.f0fee9/framework/db/CDbCommand.php(1285): CDbCommand->execute(Array)
#1 /srv/webapp/releases/20150406012619/protected/commands/UpdateRatesCommand.php(54): CDbCommand->update('{{currencies}}', Array, 'code=:code', Array)

**Comment by JuanMenendezBuitrago** [comment]
Yes. It seems like sometimes the API returns "N/A" and beaks the query. I added a try/catch and the debug function that you mentioned. Now if something goes wrong with the query of some currency pair it skips it and continues with the rest.

**Comment by atrandafir** [comment]
Okay if it is ready change the status to ready-to-test.

By the way, for future console commands I've made a parent Command we can extend.

https://github.com/thegooddata/webapp/blob/master/TGD/protected/components/TGDCommand.php

You can see we will automatically have the debug function created.

To use it you simply extend from that class instead of the original Yii class, example:
https://github.com/thegooddata/webapp/blob/master/TGD/protected/commands/FakeDataGeneratorCommand.php

So you can use $this->debug('message') from the command, and when you call the command if you want to show information on screen you simply add --debug=1.
